name: weather_app_mway
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.0
  geolocator: ^9.0.2
  go_router: ^6.4.0
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
